export const GET_CONNATCTS_LOAD="GET_CONTACTS_LOAD"
export const GET_CONNATCTS_SUCCESS="GET_CONTACTS_SUCCESS"
export const GET_CONNATCTS_FAIL="GET_CONTACTS_FAIL"



export const DELETE_CONTACT="DELTET_CONTACT"


export const GET_CONTACT="GET_CONTACT"